# 서버 설정
server:
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false

# web서비스 설정
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    pathmatch:
      matching-strategy: ant-path-matcher # swagger-ui 사용하기 위한 설정
  # Redis connection configuration
  data:
    redis: 
      host: 192.168.0.180
      port: 6001
      password: master
      cluster:
        nodes: 192.168.0.180:6001,192.168.0.180:6002,192.168.0.180:6003,192.168.0.180:6004,192.168.0.180:6005,192.168.0.180:6006,192.168.0.180:6007,192.168.0.180:6008,192.168.0.180:6009
        max-redirects: 1500
  kafka:
    #bootstrap-servers: 192.168.0.181:9092,192.168.0.181:9093,192.168.0.181:9094
    consumer:
      # consumer bootstrap servers가 따로 존재하면 설정
      bootstrap-servers: 192.168.0.181:9092,192.168.0.181:9093,192.168.0.181:9094

      # 식별 가능한 Consumer Group Id
      group-id: itapi
      # Kafka 서버에 초기 offset이 없거나, 서버에 현재 offset이 더 이상 존재하지 않을 경우 수행할 작업을 설정
      # latest: 가장 최근에 생산된 메시지로 offeset reset
      # earliest: 가장 오래된 메시지로 offeset reset
      # none: offset 정보가 없으면 Exception 발생
      auto-offset-reset: earliest
      # 데이터를 받아올 때, key/value를 역직렬화
      # JSON 데이터를 받아올 것이라면 JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      # producer bootstrap servers가 따로 존재하면 설정
      bootstrap-servers: 192.168.0.181:9092,192.168.0.181:9093,192.168.0.181:9094

      # 데이터를 보낼 때, key/value를 직렬화
      # JSON 데이터를 보낼 것이라면 JsonDeserializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


# 데이터 수집을 위한 설정
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, gateway, openapi, swagger-ui
        
# 로그 레벨 설정
logging:
#  file: 
#    name: ./logs/file.log
  level:
    root: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"


# swagger-ui custom path
#springdoc:
#  swagger-ui:
#    enabled: true
##    path: /swagger-ui.html
#  api-docs:
#    enabled: true
##    path: /api-docs
#  show-actuator: true
#  use-management-port: true 